### ISSUE TITLE
Attribute error in conformer.py

### ISSUE THREAD

**Issue by chutianxu** [lucidrains/conformer#6]
Hello Lucidrains, thank you for your wonderful work!

When I followed the usage of README by:

```
import torch
from conformer import ConformerBlock

block = ConformerBlock(
    dim = 512,
    dim_head = 64,
    heads = 8,
    ff_mult = 4,
    conv_expansion_factor = 2,
    conv_kernel_size = 31,
    attn_dropout = 0.,
    ff_dropout = 0.,
    conv_dropout = 0.
)

x = torch.randn(1, 1024, 512)
block(x) # (1, 1024, 512)
```

Some Attribute Error happened:

```
Traceback (most recent call last):
  File "/home/xxx/ASR/lucidrains-conformer/try.py", line 17, in <module>
    block(x) # (1, 1024, 512)
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/ASR/lucidrains-conformer/conformer/conformer.py", line 197, in forward
    x = self.attn(x, mask = mask) + x
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/ASR/lucidrains-conformer/conformer/conformer.py", line 64, in forward
    return self.fn(x, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/ASR/lucidrains-conformer/conformer/conformer.py", line 100, in forward
    dist = dist.clip(-max_pos_emb, max_pos_emb) + max_pos_emb
AttributeError: 'Tensor' object has no attribute 'clip'
```

May I ask what the problem is?

Thank you very much for your help.

**Comment by lucidrains** [comment]
@chutianxu hello! i'm not entirely sure, but i changed the function from clip to clamp

do you want to try it again?

**Comment by chutianxu** [comment]
> @chutianxu hello! i'm not entirely sure, but i changed the function from clip to clamp
> 
> do you want to try it again?

Hello Lucidrains, thank you very much for your quick reply and kind help.

Yes, it works after changing the function from clip to clamp.
Thank you again for your wonderful work! ^^

By the way, I am sorry but I am afraid that you may forget to change the code:
```
dist = dist.clamp(-max_pos_emb, max_pos_emb) + max_pos_emb
```
where is in Line 100 of conformer.py.
